import {
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  Tooltip,
  Legend,
  BarChart,
  Bar,
  XAxis,
 YAxis,
  CartesianGrid,
} from "recharts";

import type { SecuritySummary } from "../../api/security";

interface Props {
  summary: SecuritySummary;
}

const COLORS = [
  "#ef4444",
  "#f97316",
  "#facc15",
  "#22c55e",
];

export default function SecurityCharts({
  summary,
}: Props) {
  const severityData = [
    {
      name: "Critical",
      value: summary.findings.critical,
    },
    {
      name: "High",
      value: summary.findings.high,
    },
    {
      name: "Medium",
      value: summary.findings.medium,
    },
    {
      name: "Low",
      value: summary.findings.low,
    },
  ];

  const toolData = [
    {
      tool: "Gitleaks",
      Passed: summary.tools.gitleaks.passed,
      Failed: summary.tools.gitleaks.failed,
    },
    {
      tool: "Trivy",
      Passed: summary.tools.trivy.passed,
      Failed: summary.tools.trivy.failed,
    },
    {
      tool: "Semgrep",
      Passed: summary.tools.semgrep.passed,
      Failed: summary.tools.semgrep.failed,
    },
  ];

  const totalFindings = severityData.reduce(
    (sum, item) => sum + item.value,
    0
  );

  return (
    <div className="grid gap-8 xl:grid-cols-2">

      {/* ====================================================== */}
      {/* Vulnerability Distribution */}
      {/* ====================================================== */}

      <div className="rounded-3xl border border-slate-800 bg-slate-900 p-8 shadow-2xl transition-all duration-300 hover:border-blue-500 hover:shadow-blue-500/20">

        <div className="mb-8">

          <h2 className="text-2xl font-bold text-white">

            Vulnerability Distribution

          </h2>

          <p className="mt-2 text-slate-400">

            Current vulnerability breakdown across all repositories.

          </p>

        </div>

        <ResponsiveContainer
          width="100%"
          height={430}
        >
          <PieChart>

            <text
              x="50%"
              y="46%"
              textAnchor="middle"
              fill="#ffffff"
              fontSize="46"
              fontWeight="700"
            >
              {totalFindings}
            </text>

            <text
              x="50%"
              y="56%"
              textAnchor="middle"
              fill="#94a3b8"
              fontSize="16"
            >
              Findings
            </text>

            <Pie
              data={severityData}
              dataKey="value"
              nameKey="name"
              innerRadius={90}
              outerRadius={140}
              paddingAngle={4}
              animationDuration={1200}
              labelLine={false}
              label={({ percent }) =>
                `${((percent ?? 0) * 100).toFixed(0)}%`
              }
            >
              {severityData.map((_, index) => (
                <Cell
                  key={index}
                  fill={COLORS[index]}
                />
              ))}
            </Pie>

            <Tooltip
              contentStyle={{
                background: "#0f172a",
                border: "1px solid #334155",
                borderRadius: 18,
                color: "#fff",
                padding: "12px",
                boxShadow:
                  "0 25px 50px rgba(0,0,0,.45)",
              }}
            />

            <Legend
              wrapperStyle={{
                color: "#CBD5E1",
                paddingTop: 24,
                fontSize: 14,
              }}
            />

          </PieChart>

        </ResponsiveContainer>

      </div>

      {/* ====================================================== */}
      {/* Scanner Performance */}
      {/* ====================================================== */}

      <div className="rounded-3xl border border-slate-800 bg-slate-900 p-8 shadow-2xl transition-all duration-300 hover:border-blue-500 hover:shadow-blue-500/20">

        <div className="mb-8">

          <h2 className="text-2xl font-bold text-white">

            Scanner Performance

          </h2>

          <p className="mt-2 text-slate-400">

            Passed versus failed scans generated by security scanners.

          </p>

        </div>

        <ResponsiveContainer
          width="100%"
          height={430}
        >
          <BarChart
            data={toolData}
            barGap={16}
            barCategoryGap="30%"
          >

            <CartesianGrid
              stroke="#334155"
              strokeDasharray="4 4"
              opacity={0.35}
            />

            <XAxis
              dataKey="tool"
              stroke="#94a3b8"
              tick={{
                fill: "#cbd5e1",
                fontSize: 13,
              }}
            />

            <YAxis
              stroke="#94a3b8"
              tick={{
                fill: "#cbd5e1",
                fontSize: 13,
              }}
            />

            <Tooltip
              contentStyle={{
                background: "#0f172a",
                border: "1px solid #334155",
                borderRadius: 18,
                color: "#fff",
                padding: "12px",
                boxShadow:
                  "0 25px 50px rgba(0,0,0,.45)",
              }}
            />

            <Legend
              wrapperStyle={{
                color: "#CBD5E1",
                paddingTop: 20,
                fontSize: 14,
              }}
            />

            <Bar
              dataKey="Passed"
              fill="#22c55e"
              radius={[12, 12, 0, 0]}
              animationDuration={1200}
            />

            <Bar
              dataKey="Failed"
              fill="#ef4444"
              radius={[12, 12, 0, 0]}
              animationDuration={1200}
            />

          </BarChart>

        </ResponsiveContainer>

      </div>

    </div>
  );
}