import { useEffect, useState } from "react";

import {
  securityScansApi,
  type ScanSummary,
} from "../api/security-scans";

import {
  SecurityScansTable,
} from "../modules/security-scans";

import SecuritySummary from "../modules/security-scans/components/SecuritySummary";

export default function SecurityScansPage() {
  const [summary, setSummary] =
    useState<ScanSummary | null>(null);

  useEffect(() => {
    securityScansApi
      .getSummary()
      .then(setSummary)
      .catch(console.error);
  }, []);

  return (
  <div className="space-y-8">

    {/* Hero */}

    <div className="rounded-3xl bg-gradient-to-r from-slate-900 via-slate-800 to-slate-900 p-8 text-white shadow-xl">

      <div className="flex flex-col gap-8 xl:flex-row xl:items-center xl:justify-between">

        <div className="flex items-center gap-5">

          <div className="flex h-20 w-20 items-center justify-center rounded-3xl bg-red-600 text-5xl shadow-lg">
            🛡️
          </div>

          <div>

            <h1 className="text-4xl font-bold">
              Security Scans
            </h1>

            <p className="mt-2 max-w-2xl text-slate-300">
              Review security scan results generated by Trivy,
              Semgrep, Gitleaks, Checkov and OWASP Dependency Check.
            </p>

          </div>

        </div>

      </div>

    </div>

    {summary && (
      <SecuritySummary summary={summary} />
    )}

    <SecurityScansTable />

  </div>
);
}